[DEFAULT]
#Where to find the .hy file with training data
ReconstructionType=Regression
#InputPath=/fast_scratch/fcormier//t2k/ml/skdetsim/oct20_eMuPosPion_0dwallCut_flat_1/
#InputPath=/data/fcormier/sk/stopMu/fullSample/
#InputPath=/data/fcormier/t2k/ml/data/aug19_electrons_2GeV_2M_combine/
InputPath=/fast_scratch_2/fcormier/t2k/ml/data/oct20_combine_flatE/
#InputPath=/fast_scratch_2/fcormier/sk/MC/raw/
#InputPath=/fast_scratch_2/fcormier/t2k/ml/data/oct24_eMuPiPlus_fq_1/
#MLMCPath=/fast_scratch_2/fcormier/t2k/ml/training/finalTrainings_2GeV/resnet_oct7_muon_momentum_NoDeadPMTs_circularResnet50_new2GData_FC_1000Scale_1/14102024-034616/stopMu_MC_1000TC15000/
#MLDataPath=/fast_scratch_2/fcormier/t2k/ml/training/finalTrainings_2GeV/resnet_oct7_muon_momentum_NoDeadPMTs_circularResnet50_new2GData_FC_1000Scale_1/14102024-034616/stopMu_data_1000TC15000/
MLMCPath=/fast_scratch_2/fcormier/t2k/ml/training/finalTrainings_2GeV/resnet_sep28_muons_position_noDeadPMTs_seed_gt200Hits_fullyContained_4p5MNewData_timeO400S1000_2/12102024-015838/stopMu_MC_1000CT15000/
#MLMCPath=/fast_scratch_2/fcormier/t2k/ml/training/resnet_jan8_muons_positions_minus50cmFC_noDeadPMTs_seed_gt200Hits_flatVE_6MMNewData_timeO400S1000_1/09012025-110925/stopMu_MC_1000CT15000/
#MLMCPath=/fast_scratch_2/fcormier/t2k/ml/training/resnet_jan6_muons_positions_minus50cmFC_noDeadPMTs_seed_gt200Hits_flatVE_3p5MNewData_timeO400S1000_1/06012025-160338/stopMu_MC/
#MLMCPath=/fast_scratch_2/fcormier/t2k/ml/training/finalTrainings_2GeV/resnet_oct18_eMuPosPions_class_NoDeadPMTs_circularResnet50_new2GData_FC_1000Scale_1/17102024-231800//stopMu_MC/
aux_MLMCDir=/fast_scratch_2/fcormier/t2k/ml/training/finalTrainings_2GeV/resnet_sep28_muons_directions_noDeadPMTs_seed_gt200Hits_fullyContained_4p5MNewData_timeO400S1000_2/12102024-072239//stopMu_MC_1000TC15000/
aux_MLMCPos=/fast_scratch_2/fcormier/t2k/ml/training/finalTrainings_2GeV/resnet_sep28_muons_position_noDeadPMTs_seed_gt200Hits_fullyContained_4p5MNewData_timeO400S1000_2/12102024-015838/stopMu_MC_1000TC15000/
aux_MLMCMom=/fast_scratch_2/fcormier/t2k/ml/training/finalTrainings_2GeV/resnet_oct7_muon_momentum_NoDeadPMTs_circularResnet50_new2GData_FC_1000Scale_1/14102024-034616/stopMu_MC_1000TC15000/
aux_MLDataDir=/fast_scratch_2/fcormier/t2k/ml/training/finalTrainings_2GeV/resnet_sep28_muons_directions_noDeadPMTs_seed_gt200Hits_fullyContained_4p5MNewData_timeO400S1000_2/12102024-072239//stopMu_data_1000TC15000/
aux_MLDataPos=/fast_scratch_2/fcormier/t2k/ml/training/finalTrainings_2GeV/resnet_sep28_muons_position_noDeadPMTs_seed_gt200Hits_fullyContained_4p5MNewData_timeO400S1000_2/12102024-015838/stopMu_data_1000TC15000/
aux_MLDataMom=/fast_scratch_2/fcormier/t2k/ml/training/finalTrainings_2GeV/resnet_oct7_muon_momentum_NoDeadPMTs_circularResnet50_new2GData_FC_1000Scale_1/14102024-034616/stopMu_data_1000TC15000/
MLDataPath=/fast_scratch_2/fcormier/t2k/ml/training/finalTrainings_2GeV/resnet_sep28_muons_position_noDeadPMTs_seed_gt200Hits_fullyContained_4p5MNewData_timeO400S1000_2/12102024-015838/stopMu_data_1000CT15000/
#MLDataPath=/fast_scratch_2/fcormier/t2k/ml/training/resnet_jan8_muons_positions_minus50cmFC_noDeadPMTs_seed_gt200Hits_flatVE_6MMNewData_timeO400S1000_1/09012025-110925/stopMu_data_1000CT15000/
#MLDataPath=/fast_scratch_2/fcormier/t2k/ml/training/resnet_jan6_muons_positions_minus50cmFC_noDeadPMTs_seed_gt200Hits_flatVE_3p5MNewData_timeO400S1000_1/06012025-160338/stopMu_data/
#MLDataPath=/fast_scratch_2/fcormier/t2k/ml/training/finalTrainings_2GeV/resnet_oct18_eMuPosPions_class_NoDeadPMTs_circularResnet50_new2GData_FC_1000Scale_1/17102024-231800//stopMu_data/
FQMCPath=/fast_scratch_2/fcormier/sk/MC/fitqun_qtot/
FQMCSecondariesPath=/fast_scratch_2/fcormier/sk/stopMu/fiTQun/mc/fitqun_combine_withSecondaries.hy
FQDataPath=/fast_scratch_2/fcormier/sk/data/fitqun/
FQDataSecondariesPath=/fast_scratch_2/fcormier/sk/stopMu/fiTQun/data/fitqun_combine_withSecondaries.hy
#For subevent information
MLMCsubeventInfo=/fast_scratch_2/fcormier/sk/stopMu/mc/secondaries_combine.hy
MLDatasubeventInfo=/fast_scratch_2/fcormier/sk/stopMu/data/secondaries_combine.hy
#One of these should be true
#Where to output logs, best model, etc...
#OutputPlotPath=/data/fcormier/t2k/ml/training/plots/resnet_elec_directions_mar19_scan_best_1/
OutputPlotPath=/data/fcormier/t2k/ml/training/plots/finalTrainings_2GeV/stopMu_dataMC_jan24_fqCuts2_muon_positions_reg_1/
#OutputPlotPath=/data/fcormier/t2k/ml/training/plots/resnet_elec_momentum_mar21_scan_best_1/
#Muons
#OutputPlotPath=/data/fcormier/t2k/ml/training/plots/resnet_muons_momentum_apr5_scan_best_1/
#OutputPlotPath=/data/fcormier/t2k/ml/training/plots/resnet_muons_directions_apr5_scan_best_1/
#OutputPlotPath=/data/fcormier/t2k/ml/training/plots/resnet_may26_eMuPiPlus_classification_1/
PlotName=stopMu
OutputStatsPath=outputs/stats/
doML=True
doFiTQun=True
doCombination=True
doVarPlots=False
doOutputPlots=True
getfiTQunTruth=False
doDataMC=True

[Regression]
target=positions
#mlPath=/data/fcormier/training/resnet_mar11_reg_electrons_dir_g200Hits_scheduler_5M_1/11032024-135348/
#mlPath=/data/fcormier/training/resnet_jun26_muons_momenta_gt200Hits_timeO400S1000_2GeV_2M_1/26062024-193705/
#mlPath=/fast_scratch_2/fcormier/t2k/ml/training/finalTrainings_2GeV/resnet_sep28_muons_position_noDeadPMTs_seed_gt200Hits_fullyContained_4p5MNewData_timeO400S1000_2/12102024-015838/pg_noDeadPMTs/
mlPath=/fast_scratch_2/fcormier/t2k/ml/training/resnet_jan6_muons_positions_minus50cmFC_noDeadPMTs_seed_gt200Hits_flatVE_3p5MNewData_timeO400S1000_1/06012025-160338/particleGun_noDeadPMTs/
#mlPath=/data/fcormier/training/resnet_mar21_reg_electrons_mom_g200Hits_scheduler_5M_1/21032024-165947/
#Muons
#mlPath=/data/fcormier/training/resnet_apr5_muons_mom_regression_1/06042024-181244/
#mlPath=/data/fcormier/training/resnet_apr5_muons_dir_regression_1/05042024-171143/
#mlPath=/data/fcormier/training/resnet_apr5_muons_pos_regression_1/05042024-151006/
#Pions
#mlPath=/data/fcormier/t2k/ml/training/resnet_may5_piPlus_pos_reg_test_1/05052024-164342/
#fitqunPath=/fast_scratch/fcormier//t2k/ml/training/resnet_nov7_eMuPosPions_0dwall_1M_flat_1/06112023-205208/
#fitqunPath=/data/fcormier/sk/stopMu/
fitqunPath=/fast_scratch_2/fcormier/t2k/ml/data/oct20_combine_flatE/
particleLabel=0
doClassification=False
doRegression=True

[Classification]
#mlPath=/data/fcormier/training/stopMu_resnet_apr13_eMuPiPlus_classification_1/14042024-000620/
mlPath=/fast_scratch_2/fcormier/t2k/ml/training/finalTrainings_2GeV/resnet_oct18_eMuPosPions_class_NoDeadPMTs_circularResnet50_new2GData_FC_1000Scale_1/17102024-231800/pg_newFQ/
#fitqunPath=/fast_scratch_2/fcormier/sk/MC/fitqun/
fitqunPath=/fast_scratch_2/fcormier/t2k/ml/data/oct24_eMuPiPlus_fq_1/
#fitqunPath=/data/fcormier/sk/stopMu/
#fitqunPath=/fast_scratch_2/fcormier/t2k/ml/data/oct20_combine_flatE/
doClassification=True
doRegression=False
signalLabels = 0
bkgLabels= 2