[DEFAULT]
#Where to find the .hy file with training data
InputPath=/scratch/fcormier/t2k/ml/output_skdetsim/may29_2025_muons_pg_combine_1/scratch/fcormier/t2k/ml/output_skdetsim/may29_2025_muons_pg_combine_1//multi_combine.hy
#InputPath=/scratch/fcormier//t2k/ml/output_skdetsim//jun12_electronsCombine_1/multi_combine.hy
#Where to find indices files
#IndicesFile=/fast_scratch/WatChMaL/data/T2K/nov18_emu_fullCylinder_500k_1/train0.7_val0.15_test0.15000000000000005.npz
#IndicesFile=/scratch/fcormier/t2k/ml/output_skdetsim/jan28_electronsOnly_5M/train_val_test_gt200Hits_FC_nFolds30_fold0.npz
#IndicesFile=/scratch/fcormier/t2k/ml/output_skdetsim/apr3_eMuPiPlus_1500MeV_2M_1/train_val_test_gt200Hits_fullyContained_1200MeVCut_piPlusOnly_nFolds20_fold0.npz
#IndicesFile=/scratch/fcormier/t2k/ml/output_skdetsim/sep26_electrons_2GeV_seed_combine_6M/train_val_test_gt200Hits_fullyContained_1000MeVCut_electronsOnly_nFolds30_fold0.npz
#IndicesFile=/scratch/fcormier/t2k/ml/output_skdetsim/oct11_eMuPosPions_2GeV_seed_1M_combine_1/train_val_test_gt200Hits_2000MeVCut_eMuPosPions_nFolds30_fold0.npz
#3class
#IndicesFile=/scratch/fcormier/t2k/ml/output_skdetsim/mar8_eMuPiPlus_full_combine_1/train_val_test_gt200Hits_fcM50_2000MeVCut_nFolds30_fold0.npz
#Mu
#IndicesFile=/scratch/fcormier/t2k/ml/output_skdetsim/may29_2025_muons_pg_combine_1//train_val_test_gt200Hits_fcM50_2000MeVCut_nFolds30_fold0.npz
IndicesFile=/scratch/fcormier/t2k/ml/output_skdetsim/apr29_2026_muons_plusMay29_2025_muons_0to150MeV_additional_combine_1//train_val_test_gt100Hits_fcM50_2000MeVCut_nFolds60_fold0.npz
#Where to output logs, best model, etc...
OutputPath=/scratch/fcormier/t2k/ml/training/resnet50_may13_2026_muons_regression_positions_additionalLowE_fullCombine_trigTimeShift34_noDeadPMTs_seed_gt100Hits_flatVE_6MMNewData_10kVal_kernel3_timem600Sh1000Sc_1/
ConfigName=t2k_resnet_train.yaml
#NetworkArchitecture tells parser which other section to look into for settings
#ResNet and PointNet
NetworkArchitecture=ResNet
DoClassification=False
DoRegression=True
batchSystem=True
LearningRate=0.02
stride=1
kernelSize=3
#How much learning rate is reduced by each epoch
LearningRateDecay=0.8
#Non-zero weight decay adds regularization to the optimizer
WeightDecay=0.000000001

#If network architecture chosen as ResNet, will use these custom options
[ResNet]
UseTime=True
Classifier=Passthrough
FeatureExtractor=watchmal.model.resnet.resnet50
DataModel=T2KCNNDataset
PMTPositionsFile=data/sk_wcsim_imagefile.npy

#If network architecture chosen as PointNet, will use these custom options
[PointNet]
UseTime=True
Classifier=PointNetFullyConnected
FeatureExtractor=PointNetFeat
DataModel=PointNetT2KDataset
